version: '2'

services:
  traefik:
    image: traefik
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - "/etc/traefik/acme/acme.json:/etc/traefik/acme/acme.json"
      - "./traefik.toml:/etc/traefik/traefik.toml"
      - "/var/run/docker.sock:/var/run/docker.sock"
    labels:
      - "traefik.enable=false"
    networks:
      - traefik-proxy

  db:
    image: mariadb:10.4
    ports:
      - "127.0.0.1:3306:3306"
    environment:
      - "MYSQL_ROOT_PASSWORD=password"
      - "MYSQL_DATABASE=dev"
    volumes:
      - "./.data/mysql:/var/lib/mysql"
    labels:
      - "traefik.enable=false"
    networks:
      - traefik-proxy

  base:
    build: .
    image: info.base
    environment:
      - "NODE_ENV=production"
      - "API_HOST=api.bigj.dev"

  api:
    image: info.base
    entrypoint: "node api/index.js"
    environment:
      - "PORT=5000"
      - "NODE_ENV=production"
    labels:
      - "traefik.enable=true"
      - "traefik.port=5000"
      - "traefik.frontend.rule=Host:api.bigj.dev"
    volumes:
      - "$UPLOAD_PATH:/opt/app/.data/files"
    networks:
      - traefik-proxy

  static:
    image: info.base
    entrypoint: "node src/index.js"
    environment:
      - "PORT=5000"
      - "NODE_ENV=production"
    labels:
      - "traefik.enable=true"
      - "traefik.port=5000"
      - "traefik.frontend.rule=Host:f.bigj.dev"
    volumes:
      - "$UPLOAD_PATH:/opt/app/.data/files"
    networks:
      - traefik-proxy

networks:
  traefik-proxy:
    external:
      name: traefik-proxy
