version: '2'

services:
  traefik:
    image: traefik
    ports:
      - "443:443"
      - "80:80"
    volumes:
#      - "/etc/traefik/acme/acme.json:/etc/traefik/acme/acme.json"
      - "./traefik.toml:/etc/traefik/traefik.toml"
      - "/var/run/docker.sock:/var/run/docker.sock"
    labels:
      - "traefik.enable=false"

  db:
    image: mariadb:10.4
    ports:
      - "127.0.0.1:3306:3306"
    environment:
      - "MYSQL_ROOT_PASSWORD=password"
      - "MYSQL_DATABASE=info"
    volumes:
      - "/var/lib/mysql:/var/lib/mysql"
    labels:
      - "traefik.enable=false"

  base:
    build: .
    image: info.base
    environment:
      - "NODE_ENV=production"

  api:
    image: info.base
    entrypoint: "npm run api"
    environment:
      - "PORT=5000"
      - "NODE_ENV=production"
    labels:
      - "traefik.enable=true"
      - "traefik.port=5000"
      - "traefik.frontend.rule=Host:api.bigj.info"
    volumes:
      - "$UPLOAD_PATH:/opt/app/.data/"

  static:
    image: info.base
    entrypoint: "npm run start"
    environment:
      - "PORT=5000"
      - "NODE_ENV=production"
    labels:
      - "traefik.enable=true"
      - "traefik.port=5000"
      - "traefik.frontend.rule=Host:f.bigj.info"
    volumes:
      - "$UPLOAD_PATH:/opt/app/.data/"
