version: '2'

services:
  traefik:
    image: "traefik:v2.0.0-rc3"
    container_name: "traefik"
    command:
      - "--providers.docker=true"
      - "--api.insecure=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.http.address=:80"
      - "--entrypoints.https.address=:443"
      - "--certificatesresolvers.tls.acme.httpchallenge=true"
      - "--certificatesresolvers.tls.acme.httpchallenge.entrypoint=http"
      - "--certificatesresolvers.tls.acme.email=${ACME_EMAIL}"
      - "--certificatesresolvers.tls.acme.storage=/letsencrypt/acme.json"
    ports:
      - "80:80"
      - "443:443"
    labels:
      - "traefik.enable=true"

      - "traefik.http.middlewares.redirect.redirectregex.regex=^http://(.*)"
      - "traefik.http.middlewares.redirect.redirectregex.replacement=https://$$1"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "${CONFIG_PATH}/acme.json:/letsencrypt/acme.json"
    networks:
      - traefik-proxy

  db:
    image: mariadb:10.4
    dns: [ 8.8.8.8 ]
    ports:
      - "127.0.0.1:3306:3306"
    environment:
      - "MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}"
      - "MYSQL_DATABASE=dev"
    volumes:
      - "${CONFIG_PATH}/mysql:/var/lib/mysql"
    labels:
      - "traefik.enable=false"
    networks:
      - traefik-proxy

  api:
    build: api
    dns: [ 8.8.8.8 ]
    environment:
      - "PORT=5000"
      - "NODE_ENV=production"

      - "API_ROOT_PASSWORD=${API_ROOT_PASSWORD}"
    labels:
      - "traefik.enable=true"

      - "traefik.http.routers.dev-api-http.rule=Host(`${API_DOMAIN}`) && PathPrefix(`/graphql`,`/f/`)"
      - "traefik.http.routers.dev-api-http.entrypoints=http"
      - "traefik.http.routers.dev-api-http.middlewares=redirect"

      - "traefik.http.routers.dev-api.rule=Host(`${API_DOMAIN}`) && PathPrefix(`/graphql`,`/f/`)"
      - "traefik.http.routers.dev-api.entrypoints=https"
      - "traefik.http.routers.dev-api.tls.certresolver=tls"
      - "traefik.http.services.dev-api.loadbalancer.server.port=5000"
      - "traefik.http.middlewares.dev-api.redirectscheme.scheme=https"
    volumes:
      - "$UPLOAD_PATH:/data"
    networks:
      - traefik-proxy

  frontend:
    build: frontend
    dns: [ 8.8.8.8 ]
    environment:
      - "PORT=5000"
      - "NODE_ENV=production"
    labels:
      - "traefik.enable=true"

      - "traefik.http.routers.dev-frontend-http.rule=Host(`${API_DOMAIN}`)"
      - "traefik.http.routers.dev-frontend-http.entrypoints=http"
      - "traefik.http.routers.dev-frontend-http.middlewares=redirect"

      - "traefik.http.routers.dev-frontend.rule=Host(`${API_DOMAIN}`)"
      - "traefik.http.routers.dev-frontend.entrypoints=https"
      - "traefik.http.routers.dev-frontend.tls.certresolver=tls"
      - "traefik.http.services.dev-frontend.loadbalancer.server.port=5000"
      - "traefik.http.middlewares.dev-frontend.redirectscheme.scheme=https"
    networks:
      - traefik-proxy

networks:
  traefik-proxy:
    external:
      name: traefik-proxy
